/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.ajedrez.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import ucr.ac.cr.tm2100.g3.ajedrez.controller.ControladorJuego;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Alfil;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Caballo;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Peones;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Reina;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Rey;
import ucr.ac.cr.tm2100.g3.ajedrez.model.Torre;

/**
 *
 * @author Yuliana
 */
public class PanelJuego extends javax.swing.JPanel {

    private ImageIcon fondo;
    private ImageIcon pieza;
    private ControladorJuego controlador;
    private Caballo caballoN1,caballoN2;
    private Torre torre1, torre2;
    private Alfil alfil1, alfil2;
    private Rey rey;
    private Reina reina;
    private Peones peon;
    private int arregloX[] = {371, 450, 529, 609, 687, 767, 847,927};
    private int arregloY[] = {8, 90, 172,255, 338, 420, 503, 585};

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        fondo = new ImageIcon("./src/main/resources/img/tablero.png");//no se usa la de c: porque esa ruta es demi compu
        pieza = new ImageIcon("./src/main/resources/img/bishopW.png");
        torre1=new Torre(arregloX[0],arregloY[0],"negro");
        caballoN1=new Caballo(arregloX[1],arregloY[0],"negro");
        alfil1=new Alfil(arregloX[2],arregloY[0],"negro");
        rey=new Rey(arregloX[3],arregloY[0],"negro");
        reina=new Reina(arregloX[4],arregloY[0],"negro");
        alfil2=new Alfil(arregloX[5],arregloY[0],"negro");
        caballoN2=new Caballo(arregloX[6],arregloY[0],"negro");
        torre2=new Torre(arregloX[7],arregloY[0],"negro");
        
        peon = new Peones(arregloX[7],arregloY[7],"blanco");
        Image image = fondo.getImage().getScaledInstance(1350, 700, 100);//Darle un nuevo ancho y alto a la imagen
        fondo.setImage(image);//darle un ancho y alto a la imagen
    }

    public void setControlador(ControladorJuego controlador) {
        // this.controlador=controlador;
        this.addMouseListener(controlador);
    }

    public int getAncho() {
        return fondo.getIconWidth();
    }

    public int getAlto() {
        return fondo.getIconHeight();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        fondo.paintIcon(null, g, 0, 0);
        pieza.paintIcon(null, g, arregloX[3], arregloY[4]);//En x eran 366, pero no se centraba y al y le quité 35, porque le cambié el tamaño a la ventana
        torre1.dibujar(g);
        caballoN1.dibujar(g);
        alfil1.dibujar(g);
        rey.dibujar(g);
        reina.dibujar(g);
        alfil2.dibujar(g);
        caballoN2.dibujar(g);
        torre2.dibujar(g);
        peon.dibujar(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
